#!/bin/bash

libPath=`echo "/usr/local/melon_for_melang"`
installPath=""
arm=`cpp -dM /dev/null |grep __arm__`
arm=`echo $?`
macro=''
if [ '$arm' == '0' ]; then
	arm='--enable_arm32'
	macro='-DMLN_ARM32'
else
    arm=""
fi

for param in $@
do
	if [ $param == "--help" ]; then
		echo -e "\nMelang installation help."
		echo "Copyright (C) Niklaus F.Schen."
		echo "Options:"
		echo -e "\t--prefix=INSTALL_PATH"
		echo -e "\t--libprefix=LIB_INSTALL_PATH"
		exit 0
	fi
	param_prefix=`echo $param|cut -d '=' -f 1`
	param_suffix=`echo $param|cut -d '=' -f 2`
	if [ $param_prefix == "--prefix" ]; then
		installPath=$param_suffix
	fi
	if [ $param_prefix == "--libprefix" ]; then
		libPath=$param_suffix
	fi
done

test -d $libPath
if [ $? != 0 ]; then
	rm -fr Melon
	git clone https://github.com/Water-Melon/Melon.git
	cd Melon
	./configure --prefix=$libPath $arm
	make
	make install
	cd ..
fi

rm -fr $libPath/lib/libmelon.so
cc -o melang melang.c -I $libPath/include -L $libPath/lib -lmelon $macro

if [ $installPath"x" != "x" ]; then
	test -d $installPath || mkdir -p $installPath
	cp melang $installPath/
else
	cp melang /usr/bin/
fi

echo "Complete!"
echo "Thank you for using melang."
